services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: frontend
  nginx:
    image: nginx
    container_name: reverse-proxy
    ports:
      - 8080:80
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
