FROM node:16 as build-stage

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY --chown=node:node . . 

USER node

RUN npm run ci

CMD ["npm", "run", "build"]

FROM nginx:1.20-alpine

COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html

