version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: dev.dockerfile
  nginx:
    ports:
      - 8080:80
    image: nginx
    depends_on: 
      - server 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
 
