version: "3.8"
services:
  server:
    build:
      context: ./todo-backend
      dockerfile: dev.dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis:latest
    command: [redis-server, "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: frontend-de502v
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080/api/
    depends_on:
      - nginx
  nginx:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - server
      - mongo
      - redis
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
