version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: dev.dockerfile
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - frontend
